name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript check
      run: npx tsc --noEmit

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Build for production
      run: |
        export NODE_ENV=production
        npx expo prebuild --clear

    - name: Build iOS
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "⚠️ EXPO_TOKEN not set - skipping iOS build"
          exit 0
        fi
        npx eas build --platform ios --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Build Android
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "⚠️ EXPO_TOKEN not set - skipping Android build"
          exit 0
        fi
        npx eas build --platform android --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Deploy Firebase Functions
      run: |
        if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
          echo "⚠️ FIREBASE_TOKEN not set - skipping Firebase deployment"
          exit 0
        fi
        npm install -g firebase-tools
        firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}